/**
 * @file juniper_parser.c
 * @brief Juniper JunOS hierarchical configuration parser.
 *
 * JunOS uses a brace-delimited hierarchical syntax. This parser uses a
 * simple depth-tracking state machine to navigate the hierarchy without
 * a full recursive-descent parser, handling the most common security-
 * relevant stanzas.
 *
 * Detected markers: lines containing "junos" version string or the
 * characteristic "## Last commit" header.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "parser.h"
#include "model.h"
#include "common.h"

#define LINE_BUF 1024
#define MAX_DEPTH 16

/* -- detect() -------------------------------------------------------------- */
static bool juniper_detect(const char *filepath)
{
    FILE *f = fopen(filepath, "r");
    if (!f) return false;

    char line[LINE_BUF];
    int  checked = 0;
    bool found   = false;

    while (!found && checked < 30 && fgets(line, sizeof(line), f)) {
        str_trim(line);
        if (str_starts_with(line, "## Last commit") ||
            str_starts_with(line, "## Generated by") ||
            str_contains_ci(line, "junos") ||
            str_starts_with(line, "system {") ||
            str_starts_with(line, "interfaces {") ||
            str_starts_with(line, "version ") ||
            (str_starts_with(line, "set ") && str_contains_ci(line, "system")))
        {
            found = true;
        }
        checked++;
    }
    fclose(f);
    return found;
}

/* -- parse() --------------------------------------------------------------- */
static int juniper_parse(const char *filepath, DeviceModel *m)
{
    FILE *f = fopen(filepath, "r");
    if (!f) {
        LOG_ERR("juniper_parse: cannot open '%s'", filepath);
        return AUDIT_ERR_IO;
    }

    safe_strncpy(m->vendor, "juniper", sizeof(m->vendor));
    safe_strncpy(m->source_file, filepath, sizeof(m->source_file));

    char line[LINE_BUF];
    int  lineno = 0;

    /* Depth-tracking context stack */
    char ctx[MAX_DEPTH][64];
    int  depth = 0;
    for (int i = 0; i < MAX_DEPTH; i++) ctx[i][0] = '\0';

    /* Current interface being parsed */
    char cur_if[MAX_IFNAME_LEN]  = {0};
    char cur_unit[16]            = {0};

    /* Current ACL / firewall filter */
    char cur_filter[MAX_ACLNAME_LEN] = {0};
    char cur_term_action[8]          = {0};
    bool in_filter = false;

    /* Current SNMP community */
    char cur_community[MAX_COMMUNITY_LEN] = {0};

    while (fgets(line, sizeof(line), f)) {
        lineno++;
        str_trim(line);
        if (line[0] == '\0' || line[0] == '#') continue;

        /* Track braces */
        /* A line may open '{' and/or close '}' */
        char *open  = strchr(line, '{');
        char *close = strchr(line, '}');

        /* Closed block first if '}' comes before '{' */
        if (close && (!open || close < open)) {
            if (depth > 0) {
                ctx[depth][0] = '\0';
                depth--;
            }
        }

        /* Strip braces for content parsing */
        char content[LINE_BUF];
        safe_strncpy(content, line, sizeof(content));
        {
            char *p = strchr(content, '{');
            if (p) *p = '\0';
            p = strchr(content, '}');
            if (p) *p = '\0';
            p = strchr(content, ';');
            if (p) *p = '\0';
            str_trim(content);
        }
        if (content[0] == '\0') goto update_depth;

        /* -- Context-sensitive parsing ---------------------------------- */

        /* Build a path string for easy context checks */
        char path[256] = {0};
        for (int d = 0; d <= depth && d < MAX_DEPTH; d++) {
            if (ctx[d][0]) {
                strncat(path, ctx[d], sizeof(path) - strlen(path) - 1);
                strncat(path, "/", sizeof(path) - strlen(path) - 1);
            }
        }

        /* system / host-name */
        if (str_starts_with_ci(path, "system/") &&
            str_starts_with_ci(content, "host-name ")) {
            char tok[MAX_HOSTNAME_LEN];
            if (sscanf(content + strlen("host-name "), "%127s", tok) == 1)
                safe_strncpy(m->hostname, tok, sizeof(m->hostname));
        }

        /* system / version */
        if (depth == 0 && str_starts_with_ci(content, "version ")) {
            char tok[MAX_OSVER_LEN];
            if (sscanf(content + strlen("version "), "%63s", tok) == 1)
                safe_strncpy(m->os_version, tok, sizeof(m->os_version));
        }

        /* system / services */
        if (str_contains_ci(path, "system/services/")) {
            if (str_starts_with_ci(content, "telnet"))
                m->auth.telnet_on_vty = true;
            if (str_starts_with_ci(content, "ssh")) {
                m->auth.ssh_enabled = true;
                m->auth.ssh_version = 2;
            }
            if (str_starts_with_ci(content, "http"))
                m->services.http_enabled = true;
            if (str_starts_with_ci(content, "https"))
                m->services.https_enabled = true;
        }

        /* system / authentication-order — implies AAA */
        if (str_contains_ci(path, "system/") &&
            str_starts_with_ci(content, "authentication-order"))
            m->auth.aaa_configured = true;

        /* system / root-authentication (secret) */
        if (str_contains_ci(path, "system/root-authentication") ||
            str_contains_ci(path, "root-authentication/")) {
            if (str_starts_with_ci(content, "encrypted-password") ||
                str_starts_with_ci(content, "ssh-rsa") ||
                str_starts_with_ci(content, "ssh-ecdsa"))
                m->auth.enable_secret_set = true;
            if (str_starts_with_ci(content, "plain-text-password"))
                m->auth.enable_password_set = true;
        }

        /* system / login / user */
        if (str_contains_ci(path, "system/login/"))
            m->auth.local_users_configured = true;

        /* system / ntp */
        if (str_contains_ci(path, "system/ntp/")) {
            if (str_starts_with_ci(content, "server ")) {
                char tok[MAX_IP_LEN];
                if (sscanf(content + strlen("server "), "%47s", tok) == 1 &&
                    m->ntp.server_count < MAX_NTP_SERVERS)
                    safe_strncpy(m->ntp.servers[m->ntp.server_count++],
                                 tok, MAX_IP_LEN);
            }
            if (str_starts_with_ci(content, "authentication-key"))
                m->ntp.authenticated = true;
        }

        /* system / syslog */
        if (str_contains_ci(path, "system/syslog/")) {
            if (str_starts_with_ci(content, "host ")) {
                char tok[MAX_IP_LEN];
                if (sscanf(content + strlen("host "), "%47s", tok) == 1 &&
                    tok[0] != 'l' && /* skip 'local*' */
                    m->logging.server_count < MAX_LOG_SERVERS)
                    safe_strncpy(m->logging.servers[m->logging.server_count++],
                                 tok, MAX_IP_LEN);
            }
            if (str_starts_with_ci(content, "file messages") ||
                str_starts_with_ci(content, "file "))
                m->logging.buffered_enabled = true;
        }

        /* snmp */
        if (str_starts_with_ci(path, "snmp/")) {
            m->snmp.enabled = true;
            if (m->snmp.version < SNMP_V2C) m->snmp.version = SNMP_V2C;
            if (str_starts_with_ci(content, "community ")) {
                char tok[MAX_COMMUNITY_LEN];
                if (sscanf(content + strlen("community "), "%63s", tok) == 1) {
                    safe_strncpy(cur_community, tok, sizeof(cur_community));
                }
            }
            if (str_starts_with_ci(content, "authorization read-only") ||
                str_starts_with_ci(content, "authorization read-write")) {
                bool rw = str_contains_ci(content, "write");
                if (rw)
                    safe_strncpy(m->snmp.community_rw, cur_community,
                                 MAX_COMMUNITY_LEN);
                else
                    safe_strncpy(m->snmp.community_ro, cur_community,
                                 MAX_COMMUNITY_LEN);
            }
            if (str_starts_with_ci(content, "v3"))
                m->snmp.version = SNMP_V3;
        }

        /* interfaces */
        if (str_starts_with_ci(path, "interfaces/")) {
            /* interfaces/<name>/ */
            char parts[4][64];
            int n = sscanf(path, "interfaces/%63[^/]/%63[^/]/%63[^/]/%63[^/]",
                           parts[0], parts[1], parts[2], parts[3]);
            if (n >= 1) {
                /* Track current interface */
                if (strcmp(cur_if, parts[0]) != 0) {
                    safe_strncpy(cur_if, parts[0], sizeof(cur_if));
                    cur_unit[0] = '\0';
                }
                if (n >= 2 && portable_strcasecmp(parts[1], "unit") == 0 && n >= 3) {
                    safe_strncpy(cur_unit, parts[2], sizeof(cur_unit));
                }
            }

            /* Find or create interface */
            int idx = -1;
            for (int i = 0; i < m->interface_count; i++) {
                if (portable_strcasecmp(m->interfaces[i].name, cur_if) == 0)
                    { idx = i; break; }
            }
            if (idx == -1 && cur_if[0] != '\0' &&
                m->interface_count < MAX_INTERFACES) {
                idx = m->interface_count++;
                safe_strncpy(m->interfaces[idx].name, cur_if, MAX_IFNAME_LEN);
                if (portable_strncasecmp(cur_if, "lo", 2) == 0)
                    m->interfaces[idx].is_loopback = true;
                if (str_contains_ci(cur_if, "fxp0") ||
                    str_contains_ci(cur_if, "em0") ||
                    str_contains_ci(cur_if, "me0"))
                    m->interfaces[idx].is_management = true;
            }

            if (idx >= 0) {
                Interface *iface = &m->interfaces[idx];
                if (str_starts_with_ci(content, "address ")) {
                    char tok[MAX_IP_LEN];
                    if (sscanf(content + strlen("address "), "%47s", tok) == 1) {
                        /* Strip prefix length */
                        char *slash = strchr(tok, '/');
                        if (slash) {
                            char prefix[8] = {0};
                            safe_strncpy(prefix, slash + 1, sizeof(prefix));
                            safe_strncpy(iface->subnet_mask, prefix, MAX_MASK_LEN);
                            *slash = '\0';
                        }
                        safe_strncpy(iface->ip_address, tok, MAX_IP_LEN);
                    }
                }
                if (portable_strcasecmp(content, "disable") == 0)
                    iface->shutdown = true;
                if (str_starts_with_ci(content, "description "))
                    safe_strncpy(iface->description,
                                 content + strlen("description "),
                                 sizeof(iface->description));
                if (str_starts_with_ci(content, "input-filter ") ||
                    str_starts_with_ci(content, "filter input ")) {
                    const char *fn = content + (str_starts_with_ci(content, "filter input ")
                                               ? strlen("filter input ") : strlen("input-filter "));
                    safe_strncpy(iface->acl_in, fn, MAX_ACLNAME_LEN);
                }
                if (str_starts_with_ci(content, "output-filter ") ||
                    str_starts_with_ci(content, "filter output ")) {
                    const char *fn = content + (str_starts_with_ci(content, "filter output ")
                                               ? strlen("filter output ") : strlen("output-filter "));
                    safe_strncpy(iface->acl_out, fn, MAX_ACLNAME_LEN);
                }
            }
        }

        /* firewall / filter */
        if (str_starts_with_ci(path, "firewall/family") ||
            str_starts_with_ci(path, "firewall/filter")) {
            in_filter = true;
            /* firewall/family/inet/filter/<name>/term/<term>/ */
            char n1[64], n2[64], n3[64], n4[64], n5[64], n6[64];
            n1[0]=n2[0]=n3[0]=n4[0]=n5[0]=n6[0]='\0';
            int np = sscanf(path,
                "firewall/%63[^/]/%63[^/]/%63[^/]/%63[^/]/%63[^/]/%63[^/]",
                n1, n2, n3, n4, n5, n6);

            /* Extract filter name */
            if (np >= 4 && portable_strcasecmp(n3, "filter") == 0) {
                if (strcmp(cur_filter, n4) != 0) {
                    safe_strncpy(cur_filter, n4, sizeof(cur_filter));
                    /* Ensure ACL exists */
                    bool exists = false;
                    for (int i = 0; i < m->acl_count; i++) {
                        if (portable_strcasecmp(m->acls[i].name, cur_filter) == 0)
                            { exists = true; break; }
                    }
                    if (!exists && m->acl_count < MAX_ACLS) {
                        safe_strncpy(m->acls[m->acl_count++].name,
                                     cur_filter, MAX_ACLNAME_LEN);
                    }
                }
                /* Parse term action */
                if (np >= 6 && portable_strcasecmp(n5, "term") == 0) {
                    if (str_starts_with_ci(content, "then accept"))
                        safe_strncpy(cur_term_action, "accept",
                                     sizeof(cur_term_action));
                    if (str_starts_with_ci(content, "then discard") ||
                        str_starts_with_ci(content, "then reject"))
                        safe_strncpy(cur_term_action, "deny",
                                     sizeof(cur_term_action));
                    /* Detect permit-all (no source/dest restriction, action=accept) */
                    if (str_starts_with_ci(content, "accept") &&
                        cur_term_action[0] == '\0') {
                        /* find the acl and mark it */
                        for (int i = 0; i < m->acl_count; i++) {
                            if (portable_strcasecmp(m->acls[i].name, cur_filter) == 0 &&
                                m->acls[i].entry_count < MAX_ACL_ENTRIES) {
                                AclEntry *ae = &m->acls[i].entries[m->acls[i].entry_count++];
                                ae->action = ACL_PERMIT;
                                ae->is_any_any = true;
                                safe_strncpy(ae->src_addr, "any", MAX_IP_LEN);
                                safe_strncpy(ae->dst_addr, "any", MAX_IP_LEN);
                                ae->line_number = lineno;
                                break;
                            }
                        }
                    }
                }
            }
        } else {
            in_filter = false;
        }
        (void)in_filter;

    update_depth:;
        /* Push new context if line opens a block */
        if (open && depth < MAX_DEPTH - 1) {
            depth++;
            /* Context label is the word before '{' */
            char label[64] = {0};
            char tmp[LINE_BUF];
            safe_strncpy(tmp, line, sizeof(tmp));
            char *brace = strchr(tmp, '{');
            if (brace) *brace = '\0';
            str_trim(tmp);
            /* Take the last token as context label */
            char *sp = strrchr(tmp, ' ');
            safe_strncpy(label, sp ? sp + 1 : tmp, sizeof(label));
            safe_strncpy(ctx[depth], label, sizeof(ctx[depth]));
        }
        /* Pop context if closing brace came after open */
        if (close && open && open < close) {
            if (depth > 0) { ctx[depth][0] = '\0'; depth--; }
        }
    }

    fclose(f);
    LOG_INF("juniper_parse: parsed '%s' — %d interfaces, %d ACLs",
            filepath, m->interface_count, m->acl_count);
    return AUDIT_OK;
}

/* -- Registration ---------------------------------------------------------- */

static const VendorParser s_juniper_parser = {
    .vendor_name = "juniper",
    .detect      = juniper_detect,
    .parse       = juniper_parse
};

void juniper_parser_register(void)
{
    parser_register(&s_juniper_parser);
}


